### PR TITLE
WIP: Update of jypyterlab v3 to jupytrelab v4 dependencies

### PR DESCRIPTION
**Pull request by garciagenrique**
- Update the package to be compatible with `jupyterlab=4.1` and `python=3.11`

### CODE REVIEW

**Comment by kondratyevd** [comment]
Hi @garciagenrique, I'd be very interested to have this extension installed in my JupyterLab4 deployment (Purdue CMS Analysis Facility). Please let me know when the main functionality is ready to be tested and if there is anything I can help with.

I've recently converted a couple of other extensions to JL4, but instead of using the migration script, I created a dummy extension from scratch following [this tutorial](https://jupyterlab.readthedocs.io/en/stable/extension/extension_tutorial.html#extension-tutorial), and then reimplemented the functionality in `src/*.ts` files manually. Maybe this approach can help to recreate things like CI/CD tests too.

Cheers,
Dmitry

**Comment by garciagenrique** [comment]
> Hi @garciagenrique, I'd be very interested to have this extension installed in my JupyterLab4 deployment (Purdue CMS Analysis Facility). Please let me know when the main functionality is ready to be tested and if there is anything I can help with.
> 
> I've recently converted a couple of other extensions to JL4, but instead of using the migration script, I created a dummy extension from scratch following [this tutorial](https://jupyterlab.readthedocs.io/en/stable/extension/extension_tutorial.html#extension-tutorial), and then reimplemented the functionality in `src/*.ts` files manually. Maybe this approach can help to recreate things like CI/CD tests too.
> 
> Cheers, Dmitry

Hello Dmitry !

Thanks for reaching out and for the tips!

We will let you know, don't worry. There's an increasing interest from the RUCIO community with respect to this extension, so we in the moment it's ready we will pass the notice !

Cheers,

**Comment by Soap2G** [comment]
lgtm!

**Comment by garciagenrique** [comment]
@kondratyevd we are pushing these changes upstream (rucio repo), stay tuned ! :D

**Pull request merged**
